Read me
clecardona/SDA-group-project pull request #10
Opened 2021-05-03 12:54 UTC by sangeetha-murugesan-sda9

Added ReadMe Document , Added updated ScreenShots for likes and dislikes,Added Front-end

2021-05-03 13:23 UTC, clecardona requested changes
can you correct the comments then it is ok

2021-05-03 13:23 UTC, clecardona commented on frontend/package.json
> +    "react-modal-login": "^1.3.3",
could you correct that by keeping the last version **1.4.5**  or not commiting the package.json

2021-05-03 13:23 UTC, clecardona commented on LICENSE
> -SOFTWARE.
i think we may keep the license. just copy it from the repo to your branch and commit again

2021-05-03 13:23 UTC, clecardona commented on frontend/src/pages/auth/AuthPage.jsx
>                      </div>
i think you should keep the uncommented one

2021-05-03 16:19 UTC, clecardona approved these changes

2021-05-04 08:46 UTC, Ayatj approved these changes
Approve Read Me

2021-05-04 09:44 UTC, merged